# Generated by Django 2.0.7 on 2018-07-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiroNome', models.CharField(max_length=30)),
                ('ultimoNome', models.CharField(max_length=30)),
            ],
        ),
    ]
